import Head from 'next/head'
import Image from 'next/image'
import MainSec from '../components/MainSec'
import Projects from '../components/Projects'
import Services from '../components/Services'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import React from 'react'
import ContactMe from '../components/ContactMe'

export default function Home({projects}) {
  // const [projects, setProjects] = React.useState([])
  // React.useEffect(()=>{
  //   axios.get('http://localhost:8000/projects/')
  //   .then(res => setProjects(res.data))
  //   .catch(err => console.log(err.response))
  // }, [])

  return (
    <>
    <div className='px-2 px-md-5 py-0'>
      <div className='container'>
        <Head>
          <title>Ahmed Saied</title>
          <meta name="description" content="Generated by Ahmed Saied" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MainSec />
        <Services />
        <Projects projects={projects} />
      </div>
    </div>
    <ContactMe />

    </>
  )
}

export async function getServerSideProps (context)  {

  const res = await axios.get('https://9978-102-11-95-32.ngrok.io/projects/');
  
  const projects = res.data
  return {
    props: { projects }, // will be passed to the page component as props
  };
}